config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "stashes#new"

  match '/t/:token', to: 'stashes#show', via: :get, as: :shared_stash

  # Defines the routes for the Stash resource
  resources :stashes, only: [:index, :new, :create]
  match '/stashes/:uuid',       to: 'stashes#show',    via: :get,    as: :stash
  match '/stashes/:uuid/share', to: "stashes#share",   via: :put,    as: :share_stash
  match '/stashes/:uuid',       to: 'stashes#destroy', via: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stash.rb
class Stash < ApplicationRecord
  has_one_attached :attachment

  before_create :generate_uniq_uuid

  validates :attachment, presence: true

  def generate_uniq_token
    token = generate_token
    while Stash.find_by_token(token).present?
      token = generate_token
    end
    Kredis.integer(self.class.token_key(token), expires_in: 1.hour).value = self.id
    Kredis.unique_list(stash_key).append(token)
    token
  end

  def tokens
    tokens = Kredis.unique_list(stash_key).elements
    tokens.map do |token|
      if self.class.find_by_token(token).nil?
        Kredis.unique_list(stash_key).remove(token)
        tokens.delete(token)
      end
    end
    tokens
  end

  def filename
    attachment.blob.filename if attachment.attached?
  end

  class << self
    def find_by_token(token)
      find_by(id: Kredis.integer(token_key(token)).value)
    end

    def share_link(token)
      "#{App.scheme}://#{App.host}/t/#{token}"
    end
  end

  private

  def self.token_key(token)
    "token:#{token}"
  end

  def stash_key
    "stash_tokens:#{self.id}"
  end

  def generate_token
    SecureRandom.hex(16)
  end

  def generate_uuid
    SecureRandom.uuid
  end

  def generate_uniq_uuid
    unless self.uuid?
      uuid = generate_uuid
      while Stash.exists?(uuid: uuid)
        uuid = generate_uuid
      end
      self.uuid = uuid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_not_found
    render 'shared/not_found', status: 404
  end
end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController
  before_action :get_stash,            only: [:show, :share, :destroy]
  before_action :validate_stash_exist, only: [:show, :share, :destroy]

  def index
    @stashes = Stash.all
  end

  def show
  end

  def share
    @stash.generate_uniq_token
    redirect_to stash_path(@stash.uuid)
  end

  def new
    @stash = Stash.new
  end

  def create
    @stash = Stash.new(stash_params)
    if @stash.save
      redirect_to stash_path(@stash.uuid)
    else
      render :new
    end
  end

  def destroy
    @stash.destroy
    redirect_to stashes_path
  end

  private

  def get_stash
    if params[:token].present?
      @stash = Stash.find_by_token(params[:token])
    elsif params[:uuid].present?
      @stash = Stash.find_by_uuid(params[:uuid])
    end
  end

  def validate_stash_exist
    render_not_found unless @stash
  end

  def stash_params
    params.require(:stash).permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_helper.rb
module TimeHelper

  def localized_datetime(datetime)
    I18n.l(datetime, format: :datetime_for_console) if datetime
  end

  def localized_date_with_year(timestamp)
    I18n.l(Time.at(timestamp), format: :date_with_year)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FileStashes
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container-fluid.body
      = render 'shared/navbar'
      .container.text-center
        = yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.bg-dark{ "data-bs-theme": "dark" }
  = link_to root_path, class: 'navbar-brand' do
    %h3= I18n.t('service_name')

app/views/shared/not_found.html.haml
.row
  .col-md-8.offset-md-2
    .not_found
      %h2= I18n.t('stash.messages.not_found')
      .not_found_img
        = image_tag('/not_found.jpeg', width: 400)

app/views/stashes/_share.html.haml
%h4= I18n.t('stash.labels.share_links')
%table.table.table-hover
  %tbody
    - @stash.tokens.each do |token|
      %tr
        %td= link_to Stash.share_link(token), Stash.share_link(token)

app/views/stashes/index.html.haml
.row
  .col-md-10.offset-md-1
    .stash-list
      %h2= I18n.t('stash.titles.index')
      %table#stashes-table.table.table-hover
        %thead
          %tr
            %th= I18n.t('stash.attributes.filename')
            %th= Stash.human_attribute_name(:created_at)
            %th= Stash.human_attribute_name(:updated_at)
            %th{ colspan: 2 }= I18n.t('stash.labels.actions')
        %tbody
          - @stashes.each do |stash|
            %tr
              - if stash.attachment.attached?
                %td= link_to stash.filename, stash_path(stash.uuid)
                %td= localized_datetime(stash.created_at)
                %td= localized_datetime(stash.updated_at)
                %td
                  = link_to I18n.t('stash.buttons.download'), rails_blob_path(stash.attachment, disposition: 'attachment'), class: 'btn btn-outline-dark'
                  = link_to I18n.t('stash.buttons.delete'), stash_path(stash.uuid), data: { "turbo-method": :delete }, class: 'btn btn-outline-danger'

app/views/stashes/new.html.haml
.row
  .col-md-4.offset-md-4
    .new-stash
      %h2= I18n.t('stash.titles.new')
      = form_with(model: @stash, local: true, id: 'new-stash-form') do |f|
        .input-group
          = f.file_field :attachment, class: 'form-control', id: 'stash_attachment'
          = f.submit I18n.t('stash.buttons.upload'), class: 'input-group-text'

app/views/stashes/show.html.haml
.row
  .col-md-8.offset-md-2
    .stash-info
      - if @stash.present? && @stash.attachment.attached?
        - attachment = @stash.attachment
        %h2= @stash.filename
        .stash-preview
          - if attachment.previewable?
            = image_tag(attachment.preview(resize_to_fit: [400, nil]))
          - elsif attachment.variable?
            = image_tag(attachment.variant(resize_to_fit: [400, nil]))
          - else
            %p.text-secondary= I18n.t('stash.messages.no_preview')
        %table.table.table-hover
          %tbody
            %tr
              %td=I18n.t('stash.attributes.byte_size')
              %td= attachment.blob.byte_size
            %tr
              %td=I18n.t('stash.attributes.content_type')
              %td= attachment.blob.content_type
            %tr
              %td=Stash.human_attribute_name(:created_at)
              %td= localized_datetime(attachment.blob.created_at)
        = link_to I18n.t('stash.buttons.download'), rails_blob_path(attachment.blob, disposition: "attachment"), class: "btn btn-outline-dark"
        = link_to I18n.t('stash.buttons.share'), share_stash_path(@stash.uuid), data: {"turbo-method": :put}, class: 'btn btn-outline-dark'
  .stash-share
    = render 'share'